blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/budapestdude/stats/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/budapestdude/stats/blob/master/CLAUDE.md
    about: Read the comprehensive development documentation
